### ISSUE TITLE
自動デプロイ時のUpdateFunctionConfiguration実行時にResourceConflictExceptionが発生する

### ISSUE THREAD

**Issue by iwbc-mzk** [iwbc-mzk/asken-fitbit-sync#9]
https://github.com/iwbc-mzk/asken-fitbit-sync/actions/runs/15438847195/job/43451601604

エラーログ
```
Run aws lambda update-function-configuration \
  aws lambda update-function-configuration \
    --function-name askenFitbitSync \
    --layers arn:aws:lambda:***:***:layer:AskenFitbitSyncLayer:$LAYER_VERSION \
    --handler src.lambda_function.lambda_handler
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.13.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.13.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.3/x64/lib
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    LAYER_VERSION: 17

An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:***:***:function:askenFitbitSync
```

ログにある `An update is in progress for resource` が問題点。  
この処理の直前に UpdateFunctionCode で Lambda 関数コードの更新を行っている。  
そのためこの更新処理がサーバー側で完全に完了しLambda 関数のステータスが変更される前にレイヤ更新 UpdateFunctionConfiguration が実行されて ResourceConflictException になったと思われる。
